import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { MemoryRouter } from 'react-router-dom'
import { render, screen, waitFor, fireEvent, within } from '../../../test/utils'
import { PromptLabManager } from '../ui/PromptLabManager'
import * as promptLabApi from '../api'
import type { PromptExperiment } from '../types'

vi.mock('../api', () => ({
  listExperiments: vi.fn(),
  createExperiment: vi.fn(),
  getExperiment: vi.fn(),
  getExperimentStatus: vi.fn(),
  getExperimentTrials: vi.fn(),
  getExperimentReport: vi.fn(),
  runExperiment: vi.fn(),
  cancelExperiment: vi.fn(),
  activateExperimentRecommendation: vi.fn(),
  deleteExperiment: vi.fn(),
  autoOptimize: vi.fn(),
  analyzeFeedback: vi.fn(),
}))

const listExperimentsMock = vi.mocked(promptLabApi.listExperiments)
const getExperimentMock = vi.mocked(promptLabApi.getExperiment)
const getExperimentStatusMock = vi.mocked(promptLabApi.getExperimentStatus)
const getExperimentTrialsMock = vi.mocked(promptLabApi.getExperimentTrials)
const getExperimentReportMock = vi.mocked(promptLabApi.getExperimentReport)

function renderPromptLabManager() {
  return render(
    <MemoryRouter>
      <PromptLabManager />
    </MemoryRouter>,
  )
}

function buildExperiment(overrides: Partial<PromptExperiment> = {}): PromptExperiment {
  return {
    id: 'exp-1',
    name: 'Support Bot Optimization',
    description: 'Test alternative prompts for support scenarios',
    templateId: 'template-support',
    baselineVersionId: 'ver-1',
    candidateVersionIds: ['ver-2', 'ver-3'],
    status: 'COMPLETED',
    autoGenerated: false,
    createdBy: 'admin',
    createdAt: 1710000000000,
    startedAt: 1710001000000,
    completedAt: 1710002000000,
    ...overrides,
  }
}

describe('PromptLabManager', () => {
  beforeEach(() => {
    listExperimentsMock.mockResolvedValue([
      buildExperiment(),
      buildExperiment({ id: 'exp-2', name: 'Sales Bot A/B Test', status: 'RUNNING' }),
    ])
    getExperimentMock.mockResolvedValue(buildExperiment())
    getExperimentStatusMock.mockResolvedValue({
      experimentId: 'exp-1', status: 'COMPLETED', startedAt: 1710001000000, completedAt: 1710002000000, errorMessage: null,
    })
    getExperimentTrialsMock.mockResolvedValue([])
    getExperimentReportMock.mockResolvedValue(null)
  })

  afterEach(() => {
    vi.clearAllMocks()
  })

  it('renders page title and action buttons', () => {
    renderPromptLabManager()
    expect(screen.getByText('nav.promptLab')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'New Experiment' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Refresh' })).toBeInTheDocument()
  })

  it('keeps release navigation out of the comparison workspace', () => {
    renderPromptLabManager()

    expect(screen.queryByRole('link', { name: 'common.releaseWorkflowBacklinkStep' })).not.toBeInTheDocument()
  })

  it('shows experiment list after loading', async () => {
    renderPromptLabManager()
    await waitFor(() => {
      expect(screen.getByText('Support Bot Optimization')).toBeInTheDocument()
      expect(screen.getByText('Sales Bot A/B Test')).toBeInTheDocument()
    })
  })

  it('keeps experiment identifiers inside the closed developer disclosure', async () => {
    renderPromptLabManager()
    await waitFor(() => {
      expect(screen.getByText('Support Bot Optimization')).toBeInTheDocument()
    })

    expect(screen.queryByText('template-support')).not.toBeInTheDocument()
    fireEvent.click(screen.getByText('Support Bot Optimization'))

    const technicalDetails = (await screen.findByText('promptLabPage.technicalExperiment')).closest('details')
    expect(technicalDetails).not.toHaveAttribute('open')
    expect(within(technicalDetails as HTMLElement).getByText('template-support')).toBeInTheDocument()
  })

  it('shows empty state when no experiments exist', async () => {
    listExperimentsMock.mockResolvedValueOnce([])
    renderPromptLabManager()
    await waitFor(() => {
      // Hardcoded empty message in the component
      expect(screen.getByText('No prompt-lab experiments')).toBeInTheDocument()
    })
  })

  it('still renders page when API fails', async () => {
    listExperimentsMock.mockRejectedValueOnce(new Error('HTTP 503'))
    renderPromptLabManager()
    // useQuery errors are not shown in the UI for this component — just renders empty
    await waitFor(() => {
      expect(screen.getByText('promptLabPage.unavailableTitle')).toBeInTheDocument()
    })
  })

  it('keeps the list available when one selected comparison cannot load', async () => {
    getExperimentMock.mockRejectedValueOnce(new Error('HTTP 503'))
    renderPromptLabManager()
    await screen.findByText('Support Bot Optimization')

    fireEvent.click(screen.getByText('Support Bot Optimization'))

    expect(await screen.findByText('promptLabPage.detailUnavailableTitle')).toBeInTheDocument()
    expect(screen.getByText('Sales Bot A/B Test')).toBeInTheDocument()
    expect(screen.getByText('promptLabPage.technicalError').closest('details')).not.toHaveAttribute('open')
  })

  it('shows status filter dropdown with options', () => {
    renderPromptLabManager()
    const options = screen.getAllByRole('option')
    expect(options.length).toBeGreaterThanOrEqual(4)
    const values = options.map(o => (o as HTMLOptionElement).value)
    expect(values).toContain('')
    expect(values).toContain('RUNNING')
    expect(values).toContain('COMPLETED')
    expect(values).toContain('FAILED')
  })

  it('shows New Experiment dialog when button clicked', async () => {
    renderPromptLabManager()
    fireEvent.click(screen.getByRole('button', { name: 'New Experiment' }))
    await waitFor(() => {
      // Hardcoded title in component modal
      expect(screen.getByText('Create Experiment')).toBeInTheDocument()
    })
  })
})
