export type PromptExperimentStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED'

export interface PromptExperiment {
  id: string
  name: string
  description: string
  templateId: string
  baselineVersionId: string
  candidateVersionIds: string[]
  status: PromptExperimentStatus
  autoGenerated: boolean
  createdBy: string
  createdAt: number
  startedAt: number | null
  completedAt: number | null
}

export interface PromptExperimentStatusResponse {
  experimentId: string
  status: PromptExperimentStatus
  startedAt: number | null
  completedAt: number | null
  errorMessage: string | null
}

export interface PromptTrial {
  id: string
  promptVersionId: string
  promptVersionNumber: number
  query: string
  response: string | null
  success: boolean
  score: number
  durationMs: number
  toolsUsed: string[]
  passed: boolean
  executedAt: number
}

export interface PromptVersionSummary {
  versionId: string
  versionNumber: number
  isBaseline: boolean
  totalTrials: number
  passCount: number
  passRate: number
  avgScore: number
  avgDurationMs: number
  totalTokens: number
  errorRate: number
  tierBreakdown: Record<string, unknown>
  toolUsageFrequency: Record<string, number>
}

export interface PromptRecommendation {
  bestVersionId: string
  bestVersionNumber: number
  confidence: string
  reasoning: string
  improvements: string[]
  warnings: string[]
}

export interface PromptExperimentReport {
  experimentId: string
  experimentName: string
  generatedAt: number
  totalTrials: number
  versionSummaries: PromptVersionSummary[]
  recommendation: PromptRecommendation
}

export interface PromptLabTestQueryRequest {
  query: string
  intent?: string
  domain?: string
  expectedBehavior?: string
  tags?: string[]
}

export interface PromptLabEvaluationConfigRequest {
  structuralEnabled?: boolean
  rulesEnabled?: boolean
  llmJudgeEnabled?: boolean
  llmJudgeBudgetTokens?: number
  customRubric?: string
}

export interface CreatePromptExperimentRequest {
  name: string
  description?: string
  templateId: string
  baselineVersionId: string
  candidateVersionIds: string[]
  testQueries: PromptLabTestQueryRequest[]
  evaluationConfig?: PromptLabEvaluationConfigRequest
  model?: string
  judgeModel?: string
  temperature?: number
  repetitions?: number
}

export interface AutoOptimizeRequest {
  templateId: string
  candidateCount?: number
  judgeModel?: string
}

export interface AnalyzeFeedbackRequest {
  templateId: string
  maxSamples?: number
}

export interface FeedbackWeakness {
  category: string
  description: string
  frequency: number
  exampleQueries: string[]
}

export interface PromptFeedbackAnalysis {
  totalFeedback: number
  negativeCount: number
  weaknesses: FeedbackWeakness[]
  sampleQueryCount: number
  analyzedAt: number
}
