from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class CamelModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)


class TestQueryRequest(CamelModel):
    query: str = Field(min_length=1, max_length=20_000)
    intent: str | None = Field(default=None, max_length=128)
    domain: str | None = Field(default=None, max_length=128)
    expectedBehavior: str | None = Field(default=None, max_length=5_000)
    tags: list[str] = Field(default_factory=list, max_length=50)


class EvaluationConfigRequest(CamelModel):
    structuralEnabled: bool = True
    rulesEnabled: bool = True
    llmJudgeEnabled: bool = True
    llmJudgeBudgetTokens: int = Field(default=100_000, ge=0)
    customRubric: str | None = Field(default=None, max_length=20_000)


class CreateExperimentRequest(CamelModel):
    name: str = Field(min_length=1, max_length=200)
    description: str = Field(default="", max_length=2_000)
    templateId: str = Field(min_length=1, max_length=64)
    baselineVersionId: str = Field(min_length=1, max_length=64)
    candidateVersionIds: list[str] = Field(min_length=1, max_length=50)
    testQueries: list[TestQueryRequest] = Field(min_length=1, max_length=500)
    evaluationConfig: EvaluationConfigRequest | None = None
    model: str | None = Field(default=None, max_length=128)
    judgeModel: str | None = Field(default=None, max_length=128)
    temperature: float | None = Field(default=None, ge=0, le=2)
    repetitions: int | None = Field(default=None, ge=1, le=100)


class AutoOptimizeRequest(CamelModel):
    templateId: str = Field(min_length=1, max_length=64)
    candidateCount: int | None = Field(default=None, ge=1, le=20)
    judgeModel: str | None = Field(default=None, max_length=128)


class AnalyzeFeedbackRequest(CamelModel):
    templateId: str = Field(min_length=1, max_length=64)
    maxSamples: int | None = Field(default=None, ge=1, le=500)


class ExperimentResponse(CamelModel):
    id: str
    name: str
    description: str
    templateId: str
    baselineVersionId: str
    candidateVersionIds: list[str]
    status: str
    autoGenerated: bool
    createdBy: str
    createdAt: int
    startedAt: int | None
    completedAt: int | None


class ExperimentStatusResponse(CamelModel):
    experimentId: str
    status: str
    startedAt: int | None
    completedAt: int | None
    errorMessage: str | None


class TrialResponse(CamelModel):
    id: str
    promptVersionId: str
    promptVersionNumber: int
    query: str
    response: str | None
    success: bool
    score: float
    durationMs: int
    toolsUsed: list[str]
    passed: bool
    executedAt: int


class VersionSummaryResponse(CamelModel):
    versionId: str
    versionNumber: int
    isBaseline: bool
    totalTrials: int
    passCount: int
    passRate: float
    avgScore: float
    avgDurationMs: float
    totalTokens: int
    errorRate: float
    tierBreakdown: dict[str, dict[str, float | int]]
    toolUsageFrequency: dict[str, int]


class RecommendationResponse(CamelModel):
    bestVersionId: str
    bestVersionNumber: int
    confidence: str
    reasoning: str
    improvements: list[str]
    warnings: list[str]


class ReportResponse(CamelModel):
    experimentId: str
    experimentName: str
    generatedAt: int
    totalTrials: int
    versionSummaries: list[VersionSummaryResponse]
    recommendation: RecommendationResponse


class WeaknessResponse(CamelModel):
    category: str
    description: str
    frequency: int
    exampleQueries: list[str]


class FeedbackAnalysisResponse(CamelModel):
    totalFeedback: int
    negativeCount: int
    weaknesses: list[WeaknessResponse]
    sampleQueries: list[dict[str, object]]
    analyzedAt: int


class PromptLabRunAcceptedResponse(CamelModel):
    status: str
    experimentId: str | None = None
    templateId: str | None = None
    jobId: str | None = None


class PromptLabActivationResponse(CamelModel):
    activated: bool
    templateId: str
    versionId: str
    versionNumber: int
