import { http, HttpResponse } from 'msw'
import { NOW } from './shared'

export const mockCapabilities = {
  generatedAt: NOW,
  source: 'openapi',
  paths: [
    '/api/ops/dashboard',
    '/api/ops/metrics/names',
    '/api/personas',
    '/api/prompt-templates',
    '/api/mcp/servers',
    '/api/mcp/security',
    '/api/scheduler/jobs',
    '/api/approvals',
    '/api/sessions',
    '/api/feedback',
    '/api/output-guard/rules',
    '/api/tool-policy',
    '/api/documents',
    '/api/documents/search',
    '/api/rag-ingestion/candidates',
    '/api/rag-ingestion/policy',
    '/api/admin/rag/seed-policy',
    '/api/admin/audits',
    '/api/admin/agent-specs',
    '/api/admin/sessions',
    '/api/admin/sessions/overview',
    '/api/admin/sessions/{session_id}',
    '/api/admin/sessions/{session_id}/export',
    '/api/admin/sessions/{session_id}/tags',
    '/api/admin/sessions/{session_id}/tags/{tag_id}',
    '/api/admin/users',
    '/api/admin/users/{user_id}/sessions',
    '/api/prompt-lab/experiments',
    '/api/admin/evals/runs',
    '/api/admin/evals/pass-rate',
    '/api/admin/agent-eval/cases',
    '/api/admin/platform/health',
    '/api/admin/platform/tenants',
    '/api/admin/platform/pricing',
    '/api/admin/platform/alerts/rules',
    '/api/admin/platform/alerts',
    '/api/admin/platform/cache/invalidate',
    '/api/admin/platform/cache/invalidate-key',
    '/api/admin/platform/cache/invalidate-by-pattern',
    '/api/admin/platform/users/by-email',
    '/api/admin/tenant/overview',
    '/api/admin/tenant/usage',
    '/api/admin/tenant/quality',
    '/api/admin/tenant/tools',
    '/api/admin/tenant/cost',
    '/api/admin/tenant/slo',
    '/api/admin/tenant/alerts',
    '/api/admin/tenant/quota',
    '/api/admin/capabilities',
    '/api/admin/traces',
    '/api/admin/traces/{trace_id}/spans',
    '/api/admin/metrics/ingest/mcp-health',
    '/api/admin/metrics/ingest/tool-call',
    '/api/admin/metrics/ingest/eval-result',
    '/api/admin/metrics/ingest/eval-results',
    '/api/admin/metrics/ingest/batch',
    '/api/chat',
    '/api/slack/commands',
    '/api/slack/events',
    '/api/error-report',
    '/api/v1/a2a/diagnostics',
    '/api/proactive-channels',
    '/api/admin/metrics/latency',
    '/api/admin/metrics/latency/summary',
    '/api/admin/metrics/latency/timeseries',
    '/api/admin/metrics/slo',
    '/api/admin/conversation-analytics/by-channel',
    '/api/admin/conversation-analytics/failure-patterns',
    '/api/admin/conversation-analytics/latency-distribution',
    '/api/admin/tools/stats',
    '/api/admin/tools/accuracy',
    '/api/admin/users/usage/cost',
    '/api/admin/users/usage/daily',
    '/api/admin/users/usage/by-model',
    '/api/admin/platform/cache/stats',
    '/api/admin/platform/vectorstore/stats',
    '/api/admin/rag-analytics/status',
    '/api/admin/rag-analytics/by-channel',
    '/api/admin/models',
    '/api/admin/platform/alerts/rules/{id}',
    '/api/admin/platform/alerts/{id}/resolve',
    '/api/admin/platform/alerts/evaluate',
    '/api/admin/slack-bots',
    '/api/admin/settings',
    '/api/admin/doctor',
    '/api/admin/doctor/summary',
  ],
}

export const capabilitiesHandlers = [
  http.get('/api/admin/capabilities', () => {
    return HttpResponse.json(mockCapabilities)
  }),
]
