import { http, HttpResponse } from 'msw'
import { NOW, HOUR, DAY } from './shared'

export const mockPromptExperiments = [
  {
    id: 'exp-1',
    name: 'Support Prompt v3 vs v2',
    description: 'Comparing empathy-enhanced prompt against current production version',
    templateId: 'template-support',
    baselineVersionId: 'version-2',
    candidateVersionIds: ['version-3'],
    status: 'COMPLETED' as const,
    autoGenerated: false,
    createdBy: 'admin@example.com',
    createdAt: NOW - 3 * DAY,
    startedAt: NOW - 3 * DAY + HOUR,
    completedAt: NOW - 3 * DAY + 2 * HOUR,
  },
  {
    id: 'exp-2',
    name: 'Sales Prompt Optimization',
    description: 'Auto-generated experiment to optimize sales prompt based on negative feedback',
    templateId: 'template-sales',
    baselineVersionId: 'version-1',
    candidateVersionIds: ['version-auto-1', 'version-auto-2'],
    status: 'PENDING' as const,
    autoGenerated: true,
    createdBy: 'system',
    createdAt: NOW - HOUR,
    startedAt: null,
    completedAt: null,
  },
]

export const mockPromptTrials = [
  {
    id: 'trial-1',
    promptVersionId: 'version-2',
    promptVersionNumber: 2,
    query: 'My Jira integration is broken',
    response: 'I understand the frustration. Let me check the MCP server status for Atlassian.',
    success: true,
    score: 0.78,
    durationMs: 1200,
    toolsUsed: ['jira_search'],
    passed: true,
    executedAt: NOW - 3 * DAY + HOUR + 5000,
  },
  {
    id: 'trial-2',
    promptVersionId: 'version-3',
    promptVersionNumber: 3,
    query: 'My Jira integration is broken',
    response: 'I\'m sorry to hear that. Let me look into the Jira connection right away and help get this resolved.',
    success: true,
    score: 0.92,
    durationMs: 1350,
    toolsUsed: ['jira_search'],
    passed: true,
    executedAt: NOW - 3 * DAY + HOUR + 10000,
  },
]

export const mockPromptExperimentReport = {
  experimentId: 'exp-1',
  experimentName: 'Support Prompt v3 vs v2',
  generatedAt: NOW - 3 * DAY + 2 * HOUR,
  totalTrials: 20,
  versionSummaries: [
    {
      versionId: 'version-2',
      versionNumber: 2,
      isBaseline: true,
      totalTrials: 10,
      passCount: 7,
      passRate: 0.7,
      avgScore: 0.75,
      avgDurationMs: 1180,
      totalTokens: 45000,
      errorRate: 0.1,
      tierBreakdown: { excellent: 3, good: 4, acceptable: 2, poor: 1 },
      toolUsageFrequency: { jira_search: 5, confluence_get_page: 3 },
    },
    {
      versionId: 'version-3',
      versionNumber: 3,
      isBaseline: false,
      totalTrials: 10,
      passCount: 9,
      passRate: 0.9,
      avgScore: 0.89,
      avgDurationMs: 1320,
      totalTokens: 52000,
      errorRate: 0.0,
      tierBreakdown: { excellent: 6, good: 3, acceptable: 1, poor: 0 },
      toolUsageFrequency: { jira_search: 6, confluence_get_page: 4 },
    },
  ],
  recommendation: {
    bestVersionId: 'version-3',
    bestVersionNumber: 3,
    confidence: 'HIGH',
    reasoning: 'Version 3 shows significant improvement in pass rate (+20%) and average score (+0.14) with zero errors. The empathy-enhanced prompt consistently produces more helpful and contextually aware responses.',
    improvements: ['Higher empathy scores', 'Better tool utilization', 'Zero error rate'],
    warnings: ['Slightly higher token usage (+15.5%)'],
  },
}

function getMockPromptExperiments() {
  return [
    {
      ...mockPromptExperiments[0],
      name: '고객 지원 프롬프트 v3 vs v2',
      description: '공감 강화 프롬프트와 현재 프로덕션 버전 비교',
    },
    {
      ...mockPromptExperiments[1],
      name: '영업 프롬프트 최적화',
      description: '부정적 피드백을 기반으로 영업 프롬프트를 최적화하는 자동 생성 실험',
    },
  ]
}

function getMockPromptTrials() {
  return [
    {
      ...mockPromptTrials[0],
      query: 'Jira 연동이 작동하지 않습니다',
      response: '불편을 드려 죄송합니다. Atlassian의 MCP 서버 상태를 확인해 보겠습니다.',
    },
    {
      ...mockPromptTrials[1],
      query: 'Jira 연동이 작동하지 않습니다',
      response: '불편을 끼쳐 드려 죄송합니다. Jira 연결 상태를 바로 확인하고 해결을 도와드리겠습니다.',
    },
  ]
}

function getMockPromptExperimentReport() {
  return {
    ...mockPromptExperimentReport,
    experimentName: '고객 지원 프롬프트 v3 vs v2',
    recommendation: {
      ...mockPromptExperimentReport.recommendation,
      reasoning: '버전 3이 합격률(+20%)과 평균 점수(+0.14)에서 상당한 개선을 보였으며 오류율이 0입니다. 공감 강화 프롬프트가 더 유용하고 맥락을 잘 이해하는 응답을 일관되게 생성합니다.',
      improvements: ['공감 점수 향상', '도구 활용도 개선', '오류율 제로'],
      warnings: ['토큰 사용량 소폭 증가 (+15.5%)'],
    },
  }
}

export const promptLabHandlers = [
  http.get('/api/prompt-lab/experiments', () => {
    return HttpResponse.json(getMockPromptExperiments())
  }),

  http.get('/api/prompt-lab/experiments/:id', ({ params }) => {
    const experiments = getMockPromptExperiments()
    const exp = experiments.find(e => e.id === params.id)
    if (!exp) return HttpResponse.json({ error: 'Not found' }, { status: 404 })
    return HttpResponse.json(exp)
  }),

  http.get('/api/prompt-lab/experiments/:id/status', ({ params }) => {
    const experiments = getMockPromptExperiments()
    const exp = experiments.find(e => e.id === params.id)
    if (!exp) return HttpResponse.json({ error: 'Not found' }, { status: 404 })
    return HttpResponse.json({
      experimentId: exp.id,
      status: exp.status,
      startedAt: exp.startedAt,
      completedAt: exp.completedAt,
      errorMessage: null,
    })
  }),

  http.get('/api/prompt-lab/experiments/:id/trials', () => {
    return HttpResponse.json(getMockPromptTrials())
  }),

  http.get('/api/prompt-lab/experiments/:id/report', () => {
    return HttpResponse.json(getMockPromptExperimentReport())
  }),

  http.post('/api/prompt-lab/experiments', async ({ request }) => {
    const body = await request.json() as Record<string, unknown>
    return HttpResponse.json(
      { id: 'exp-new', ...body, status: 'PENDING', autoGenerated: false, createdBy: 'admin@example.com', createdAt: NOW, startedAt: null, completedAt: null },
      { status: 201 },
    )
  }),

  http.post('/api/prompt-lab/experiments/:id/run', () => {
    return new HttpResponse(null, { status: 202 })
  }),

  http.post('/api/prompt-lab/experiments/:id/cancel', () => {
    return new HttpResponse(null, { status: 200 })
  }),

  http.delete('/api/prompt-lab/experiments/:id', () => {
    return new HttpResponse(null, { status: 204 })
  }),

  http.post('/api/prompt-lab/auto-optimize', () => {
    return HttpResponse.json({ status: 'STARTED', templateId: 'template-sales', jobId: 'exp-auto-1' })
  }),

  http.post('/api/prompt-lab/analyze', () => {
    return HttpResponse.json({
      totalFeedback: 156,
      negativeCount: 20,
      weaknesses: [
        { category: 'tool_errors', description: '도구 호출 오류를 원활하게 처리하지 못함', frequency: 8, exampleQueries: ['배포 상태 확인', '빌드 상태가 어떻게 되나요?'] },
        { category: 'verbosity', description: '단순한 질문에 대해 응답이 너무 길음', frequency: 6, exampleQueries: ['스탠드업 시간이 언제인가요?', 'DEMO 프로젝트의 PM이 누구인가요?'] },
      ],
      sampleQueryCount: 50,
      analyzedAt: NOW,
    })
  }),
]
