import { render, screen, waitFor } from '../../../test/utils'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { ExperimentsTab } from '../ui/ExperimentsTab'
import type { VersionResponse, PromptExperiment } from '../types'
import { i18n } from '../../../test/utils'

// Add promptStudio i18n keys for tests
i18n.addResourceBundle('en', 'translation', {
  'promptStudio.experimentsGuide': 'Compare prompt versions with real test queries to find the best performer.',
  'promptStudio.experimentsEmpty': 'No experiments yet',
  'promptStudio.experimentsEmptyDesc': 'Run an A/B test to compare prompt versions and find the best wording.',
  'promptStudio.newExperiment': 'New Experiment',
  'promptStudio.experimentName': 'Experiment Name',
  'promptStudio.onboarding.step1': 'Select versions to compare',
  'promptStudio.onboarding.step2': 'Add test queries your users would ask',
  'promptStudio.onboarding.step3': 'Run the experiment',
  'promptStudio.onboarding.step4': 'Review results',
  'promptStudio.onboarding.step5': 'Activate the winner',
  'promptStudio.comparisonGuide.step1Title': 'Choose current and proposed content',
  'promptStudio.comparisonGuide.step1Description': 'Pick the current content and a draft.',
  'promptStudio.comparisonGuide.step2Title': 'Add representative questions',
  'promptStudio.comparisonGuide.step2Description': 'Use questions real users ask.',
  'promptStudio.comparisonGuide.step3Title': 'Review and apply',
  'promptStudio.comparisonGuide.step3Description': 'Compare quality and apply the recommendation.',
  'promptStudio.experimentStatus.completed': 'Comparison complete',
  'promptStudio.experimentStatus.running': 'Comparing',
  'promptStudio.experimentStatus.ready': 'Ready',
  'promptStudio.experimentStatus.failed': 'Comparison failed',
  'promptStudio.experimentStatus.cancelled': 'Cancelled',
  'promptStudio.experimentStatus.unknown': 'Needs review',
  'promptStudio.running': 'Running...',
  'promptStudio.cancelExperiment': 'Cancel Experiment',
  'promptStudio.runExperiment': 'Run Experiment',
  'promptStudio.version': 'Version',
  'promptStudio.comparisonTargets': 'Comparison targets',
  'promptStudio.comparisonTargetCount': '{{count}} versions',
  'common.status': 'Status',
  'common.delete': 'Delete',
  'common.back': 'Back',
  'common.toast.created': 'Created',
}, true, true)

// Mock the API module
vi.mock('../api', () => ({
  listExperiments: vi.fn(),
  getExperiment: vi.fn(),
  createExperiment: vi.fn(),
  runExperiment: vi.fn(),
  cancelExperiment: vi.fn(),
  getExperimentStatus: vi.fn(),
  getExperimentTrials: vi.fn(),
  getExperimentReport: vi.fn(),
  activateExperimentRecommendation: vi.fn(),
  deleteExperiment: vi.fn(),
}))

import * as api from '../api'

const mockedApi = vi.mocked(api)

const mockVersions: VersionResponse[] = [
  {
    id: 'v1',
    templateId: 't1',
    version: 1,
    content: 'You are a helpful assistant.',
    status: 'ACTIVE',
    changeLog: 'Initial version',
    createdAt: 1700000000000,
  },
  {
    id: 'v2',
    templateId: 't1',
    version: 2,
    content: 'You are a concise assistant.',
    status: 'DRAFT',
    changeLog: 'Shorter',
    createdAt: 1700100000000,
  },
]

function makeExperiment(overrides: Partial<PromptExperiment> = {}): PromptExperiment {
  return {
    id: 'exp-1',
    name: 'v1 vs v2 test',
    description: 'Comparing v1 and v2',
    templateId: 't1',
    baselineVersionId: 'v1',
    candidateVersionIds: ['v2'],
    status: 'COMPLETED',
    autoGenerated: false,
    createdBy: 'admin',
    createdAt: 1700000000000,
    startedAt: 1700000010000,
    completedAt: 1700000020000,
    ...overrides,
  }
}

const defaultProps = {
  templateId: 't1',
  templateName: 'Customer Support Bot',
  versions: mockVersions,
}

describe('ExperimentsTab', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('renders empty state with onboarding guide when no experiments', async () => {
    mockedApi.listExperiments.mockResolvedValue([])

    render(<ExperimentsTab {...defaultProps} />)

    await waitFor(() => {
      expect(screen.getByText('No experiments yet')).toBeInTheDocument()
    })

    // Empty state description text
    expect(
      screen.getByText('Run an A/B test to compare prompt versions and find the best wording.'),
    ).toBeInTheDocument()

    expect(screen.getByText('Choose current and proposed content')).toBeInTheDocument()
    expect(screen.getByText('Add representative questions')).toBeInTheDocument()
    expect(screen.getByText('Review and apply')).toBeInTheDocument()
    expect(document.querySelectorAll('.prompt-comparison-guide li')).toHaveLength(3)
  })

  it('shows "New Experiment" button in empty state', async () => {
    mockedApi.listExperiments.mockResolvedValue([])

    render(<ExperimentsTab {...defaultProps} />)

    await waitFor(() => {
      expect(screen.getByText('New Experiment')).toBeInTheDocument()
    })

    const newButton = screen.getByText('New Experiment')
    expect(newButton).toBeInTheDocument()
    expect(newButton.tagName).toBe('BUTTON')
  })

  it('shows "New Experiment" button in list view header', async () => {
    const experiments = [makeExperiment()]
    mockedApi.listExperiments.mockResolvedValue(experiments)

    render(<ExperimentsTab {...defaultProps} />)

    await waitFor(() => {
      expect(screen.getByText('New Experiment')).toBeInTheDocument()
    })
  })

  it('shows DataTable with experiments filtered by templateId', async () => {
    const experiments = [
      makeExperiment({ id: 'exp-1', name: 'Experiment A', templateId: 't1' }),
      makeExperiment({ id: 'exp-2', name: 'Experiment B', templateId: 't1' }),
      makeExperiment({ id: 'exp-other', name: 'Other Template Exp', templateId: 't-other' }),
    ]
    mockedApi.listExperiments.mockResolvedValue(experiments)

    render(<ExperimentsTab {...defaultProps} />)

    await waitFor(() => {
      expect(screen.getByText('Experiment A')).toBeInTheDocument()
    })

    expect(screen.getByText('Experiment B')).toBeInTheDocument()
    // The experiment from a different template should NOT appear
    expect(screen.queryByText('Other Template Exp')).not.toBeInTheDocument()
  })

  it('shows readable experiment states without raw enums', async () => {
    const experiments = [
      makeExperiment({ id: 'exp-1', name: 'Completed Exp', status: 'COMPLETED' }),
      makeExperiment({ id: 'exp-2', name: 'Running Exp', status: 'RUNNING' }),
    ]
    mockedApi.listExperiments.mockResolvedValue(experiments)

    render(<ExperimentsTab {...defaultProps} />)

    await waitFor(() => {
      expect(screen.getByText('Comparison complete')).toBeInTheDocument()
    })

    expect(screen.getByText('Comparing')).toBeInTheDocument()
    expect(screen.queryByText('COMPLETED')).not.toBeInTheDocument()
  })

  it('shows version count in the table', async () => {
    const experiments = [
      makeExperiment({
        id: 'exp-1',
        name: 'Multi-version exp',
        candidateVersionIds: ['v2', 'v3'],
      }),
    ]
    mockedApi.listExperiments.mockResolvedValue(experiments)

    render(<ExperimentsTab {...defaultProps} />)

    await waitFor(() => {
      // 1 baseline + 2 candidates = 3 comparison targets
      expect(screen.getByText('3 versions')).toBeInTheDocument()
    })
  })

  it('renders empty state when all experiments are from other templates', async () => {
    const experiments = [
      makeExperiment({ id: 'exp-other', name: 'Other Exp', templateId: 't-other' }),
    ]
    mockedApi.listExperiments.mockResolvedValue(experiments)

    render(<ExperimentsTab {...defaultProps} />)

    await waitFor(() => {
      expect(screen.getByText('No experiments yet')).toBeInTheDocument()
    })
  })
})
