import type { ReactNode } from 'react'
import { render, type RenderOptions } from '@testing-library/react'
import { QueryClient, QueryClientProvider, MutationCache } from '@tanstack/react-query'
import i18n from 'i18next'
import { I18nextProvider, initReactI18next } from 'react-i18next'

// Minimal i18n setup for tests - returns key as translation
const testI18n = i18n.createInstance()
testI18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  resources: {
    en: {
      translation: {
        'common.readinessChecksTitle': 'Readiness checks',
        'common.readinessPassCount': '{{count}}/{{total}} passing',
        'common.cancel': 'Cancel',
        'common.confirm': 'Confirm',
        'common.delete': 'Delete',
        'common.refresh': 'Refresh',
        'common.apply': 'Apply',
        'common.reset': 'Reset',
        'common.status': 'Status',
        'common.featureDisabled': 'This feature is not available.',
        'common.draft.recoveryTitle': 'Earlier draft available',
        'common.draft.recoveryHint': 'Restore your earlier input.',
        'common.draft.accept': 'Restore',
        'common.draft.dismiss': 'Discard',
        'common.draft.savedRelative': 'saved {{time}}',
        'nav.approvals': 'Approvals',
        'nav.help.approvals': 'Manage tool call approval requests',
        'approvals.tool': 'Tool',
        'approvals.requestedAt': 'Requested At',
        'approvals.approve': 'Approve',
        'approvals.reject': 'Reject',
        'approvals.allStatuses': 'All Statuses',
        'approvals.empty': 'No pending approvals',
        'approvals.selectApproval': 'Select an approval to view details',
        'approvals.runId': 'Run ID',
        'approvals.arguments': 'Arguments',
        'approvals.rejectTitle': 'Reject Tool Call',
        'approvals.rejectMessage': 'Reject {{tool}}?',
        'approvals.reason': 'Reason',
        'approvals.reasonPlaceholder': 'Optional reason...',
        'auth.loginFailed': 'Login failed',
        'auth.adminOnly': 'Admin only',
        'auth.serverError': 'Server error',
        'auth.loginUnavailable': 'Login connection unavailable',
        'error.crashTitle': 'Something went wrong',
        'error.crashDescription': 'Try again or move to another page.',
        'error.reportHint': 'If the problem persists, contact an administrator.',
        'error.tryAgain': 'Try again',
        'error.reload': 'Reload page',
        'error.goHome': 'Go home',
        'error.offline': 'You are offline. Some features may not work.',
        'error.sectionCrashTitle': 'This section encountered an error',
        'error.sectionCrashDescription': 'Please try again or refresh the page',
        'error.sectionRetry': 'Try again',
        'common.name': 'Name',
        'common.toast.created': 'Created',
        'personas.icon': 'Icon',
        'personas.systemPrompt': 'System Prompt',
        'personas.createModal.title': 'Create Persona',
        'personas.createModal.subtitle': 'Define the personality and role of an AI assistant.',
        'personas.createModal.iconHint': 'Choose an icon to easily identify this persona in the list.',
        'personas.createModal.systemPromptHelp': 'Describe what role the AI should perform.',
        'personas.createModal.systemPromptExample': 'e.g. "You are a friendly customer service agent who responds to inquiries with care."',
        'personas.createModal.footerHint': 'Response guidelines, welcome messages, and other settings can be added after creation.',
        'personas.createModal.submit': 'Create',
        'personas.editModal.title': 'Edit Persona',
        'personas.formSection.details': 'Detailed Settings',
        'personas.formSection.descriptionHelp': 'Add a note about this persona\'s purpose.',
        'personas.formSection.guidelineHelp': 'Specify response tone, style, and constraints.',
        'personas.formSection.welcomeHelp': 'The greeting AI sends at the start of a conversation.',
        'personas.formSection.templateHelp': 'Links a prompt template to use instead of the system prompt.',
        'personas.responseGuideline': 'Response Guideline',
        'personas.responseGuidelinePlaceholder': 'Additional response style/format instructions...',
        'personas.welcomeMessage': 'Welcome Message',
        'personas.welcomeMessagePlaceholder': 'Initial greeting when persona is selected...',
        'personas.descriptionPlaceholder': 'Short description of this persona...',
        'personas.linkedPromptTemplate': 'Linked Prompt Template',
        'personas.linkedPromptTemplateNone': 'Use fallback system prompt only',
        'personas.setDefault': 'Set as default persona',
        'personas.active': 'Active',
        'personas.default': 'DEFAULT',
        'personas.inactive': 'INACTIVE',
        'personas.systemPromptHelp': 'Required. This is the core instruction that defines tone, safety, and role boundaries.',
        'personas.create': 'Create Persona',
        'personas.empty': 'No personas configured',
        'personas.selectPersona': 'Select a persona to view details',
        'personas.deleteTitle': 'Delete Persona',
        'personas.deleteConfirm': 'Delete persona "{{name}}"? This cannot be undone.',
        'personas.tabInfo': 'Info',
        'personas.tabPlayground': 'Playground',
        'common.edit': 'Edit',
        'common.save': 'Save',
        'common.close': 'Close',
        'common.savedViews.dropdownLabel': 'Saved views',
        'common.savedViews.saveCurrent': 'Save current filter…',
        'common.savedViews.namePlaceholder': 'Enter view name',
        'common.savedViews.saveAction': 'Save',
        'common.savedViews.applyAction': 'Apply',
        'common.savedViews.removeAction': 'Remove',
        'common.savedViews.removeConfirm': 'Click again',
        'common.savedViews.emptyState': 'No saved views yet',
        'common.savedViews.emptyTrigger': 'No saved views',
        'common.savedViews.viewCount': '{{count}} saved',
        'common.retry': 'Retry',
        'common.description': 'Description',
        'common.updatedAt': 'Updated At',
        'common.releaseReports.smoke_run': 'Smoke Run',
        'common.releaseReports.release_evidence': 'Release Evidence',
        'common.releaseReports.hardening_suite': 'Hardening Suite',
        'common.releaseReports.langsmith_eval_sync': 'Langsmith Eval Sync',
        'common.releaseReports.release_readiness': 'Release Readiness',
        'common.releaseReports.backend_provider_integration': 'Backend Provider Integration',
        'common.releaseReports.feedback_promotion.reviewed_feedback': 'Feedback promotion',
        'common.releaseReportFallback': 'Connected check material',
        'common.openReleaseReport': 'Open {{report}}',
        'common.toast.deleted': 'Deleted',
        'common.toast.updated': 'Updated',
        'common.toast.close': 'Close',
        'common.toast.action': 'Action',
        'common.toast.undone': 'Restored',
        'common.undo': 'Undo',
        'personas.deletedNamed': 'Deleted "{{name}}" persona',
        'mcpServers.deletedNamed': 'Deleted "{{name}}" MCP server',
        'outputGuardPage.deletedNamed': 'Deleted "{{name}}" rule',
        'prompts.deletedNamed': 'Deleted "{{name}}" template',
        'common.toast.overflowMore': '{{count}} more',
        'common.toast.overflowExpand': 'Show all',
        'common.toast.overflowCollapse': 'Collapse',
        'common.unsavedChanges': 'Unsaved changes',
        'common.unsavedChangesMessage': 'You have unsaved changes. Discard them?',
        'common.typeToConfirm': 'Type the following exactly to confirm:',
        'common.typeToConfirmHelp': 'This action is irreversible. Confirm enables only when the value matches.',
        'nav.personas': 'Personas',
        'nav.help.personas': 'Create and manage AI assistant personalities.',
        'conversations.title': 'Conversations',
        'conversations.row.msgs': '{{count}} msgs',
        'conversations.feed.title': 'Sessions',
        'conversations.feed.search': 'Search conversations...',
        'conversations.feed.totalCount': '{{count}} sessions',
        'conversations.feed.loadMore': 'Load more sessions',
        'conversations.feed.noResults': 'No sessions match your filters',
        'conversations.feed.noData': 'No conversation data yet',
        'conversations.feed.clearFilters': 'Clear filters',
        'conversations.filters.date': 'Date',
        'conversations.filters.today': 'Today',
        'conversations.filters.last7d': '7 days',
        'conversations.filters.last30d': '30 days',
        'conversations.filters.channel': 'Channel',
        'conversations.filters.persona': 'Persona',
        'conversations.filters.trust': 'Trust',
        'conversations.filters.feedback': 'Feedback',
        'conversations.filters.all': 'All',
        'conversations.filters.clean': 'Clean',
        'conversations.filters.flagged': 'Flagged',
        'conversations.filters.blocked': 'Blocked',
        'conversations.filters.positive': 'Positive',
        'conversations.filters.negative': 'Negative',
        'conversations.filters.none': 'None',
        'conversations.filters.clear': 'Clear',
        'conversations.filters.web': 'Web',
        'conversations.filters.slack': 'Slack',
        'conversations.filters.teams': 'Teams',
        'conversations.filters.discord': 'Discord',
        'nav.feedback': 'Feedback',
        'nav.help.feedback': 'Review feedback submitted by users.',
        'nav.expand': 'Expand navigation',
        'nav.collapse': 'Collapse navigation',
        'nav.navigation': 'Navigation',
        'nav.groupViewControls': 'Navigation group view',
        'nav.focusGroups': 'Show core groups',
        'nav.focusGroupsShort': 'Core',
        'nav.expandGroups': 'Expand all groups',
        'nav.expandGroupsShort': 'All',
        'nav.dashboard': 'Dashboard',
        'nav.releaseCockpit': 'Release Cockpit',
        'nav.issues': 'Issues',
        'nav.platformAdmin': 'Platform Admin',
        'nav.sessions': 'Sessions',
        'nav.audit': 'Audit',
        'nav.mcpServers': 'MCP Servers',
        'nav.chatInspector': 'Chat Inspector',
        'nav.integrations': 'Integrations',
        'nav.scheduler': 'Scheduler',
        'nav.promptStudio': 'Prompt Studio',
        'nav.documents': 'Documents',
        'nav.safetyRules': 'Safety Rules',
        'nav.group.operations': 'Operations',
        'nav.group.releaseOps': 'Release Operations',
        'nav.group.releaseOpsDesc': 'v1.1 RAG 수집, 근거 답변, feedback/eval 승격, LangSmith sync, live smoke, readiness 리포트를 release gate 순서로 닫습니다.',
        'nav.releaseStepRangeShort': 'Step {{range}}',
        'nav.group.aiConfig': 'AI Configuration',
        'nav.group.monitoring': 'Monitoring',
        'nav.group.devTools': 'Developer Tools',
        'feedbackPage.filters.allRatings': 'All ratings',
        'feedbackPage.filters.allIntents': 'All intents',
        'feedbackPage.filters.allModels': 'All models',
        'feedbackPage.filters.allTemplates': 'All templates',
        'feedbackPage.filters.from': 'From',
        'feedbackPage.filters.to': 'To',
        'feedbackPage.columns.rating': 'Rating',
        'feedbackPage.columns.id': 'ID',
        'feedbackPage.columns.intent': 'Intent',
        'feedbackPage.columns.model': 'Model',
        'feedbackPage.columns.domain': 'Domain',
        'feedbackPage.columns.comment': 'Comment',
        'feedbackPage.columns.created': 'Created',
        'feedbackPage.noData': 'No feedback data',
        'feedbackPage.emptyTitle': 'No feedback',
        'feedbackPage.emptyDesc': 'No feedback matches your filters.',
        'feedbackPage.selectTitle': 'No selection',
        'feedbackPage.selectToInspect': 'Select feedback to inspect',
        'feedbackPage.deleteTitle': 'Delete Feedback',
        'feedbackPage.deleteMessage': 'Delete feedback {{id}}?',
        'feedbackPage.export': 'Export',
        'feedbackPage.refresh': 'Refresh',
        'feedbackPage.total': 'Total',
        'feedbackPage.query': 'Query',
        'feedbackPage.response': 'Response',
        'feedbackPage.comment': 'Comment',
        'feedbackPage.metadata': 'Metadata',
        'feedbackPage.run': 'Run',
        'feedbackPage.columns.status': 'Status',
        'feedbackPage.columns.query': 'Query',
        'feedbackPage.columns.tags': 'Tags',
        'feedbackPage.filters.all': 'All',
        'feedbackPage.filters.search': 'Search',
        'feedbackPage.filters.searchPlaceholder': 'Search query/comment',
        'feedbackPage.filters.hasComment': 'Comment',
        'feedbackPage.filters.commentYes': 'With comment',
        'feedbackPage.filters.commentNo': 'Without comment',
        'feedbackPage.resultsSummary': '{{shown}} of {{total}}',
        'feedbackPage.unreviewedBadge': '{{count}} unreviewed',
        'feedbackPage.bulk.selectAll': 'Select all',
        'feedbackPage.bulk.selected': '{{count}} selected',
        'feedbackPage.bulk.markDone': 'Mark as done',
        'feedbackPage.bulk.markInbox': 'Move back to inbox',
        'feedbackPage.bulk.markDelete': 'Mark for delete',
        'feedbackPage.bulk.exportCsv': 'Export CSV',
        'feedbackPage.bulk.deleteConfirm': 'Delete {{count}} selected?',
        'feedbackPage.bulk.result': 'Updated {{updated}} · Failed {{failed}}',
        'auditPage.bulk.exportCsv': 'Export CSV',
        'auditPage.bulk.rollback': 'Bulk rollback',
        'auditPage.bulk.rollbackConfirm': 'Roll back {{count}} entries?',
        'auditPage.bulk.result': '{{ok}} ok · {{failed}} failed',
        'personas.bulk.activate': 'Bulk activate',
        'personas.bulk.deactivate': 'Bulk deactivate',
        'personas.bulk.activateResult': 'activated {{ok}} · failed {{failed}}',
        'personas.bulk.deactivateResult': 'deactivated {{ok}} · failed {{failed}}',
        'documentsPage.bulk.delete': 'Bulk delete',
        'documentsPage.bulk.deleteConfirm': 'Delete {{count}} docs?',
        'documentsPage.bulk.deleteResult': '{{count}} docs deleted',
        'documentsPage.bulk.reindex': 'Bulk reindex',
        'documentsPage.bulk.reindexConfirm': 'Reindex {{count}} docs?',
        'documentsPage.bulk.reindexResult': '{{count}} docs reindexed',
        'feedbackPage.review.title': 'Review',
        'feedbackPage.review.status': 'Status',
        'feedbackPage.review.statusInbox': 'inbox',
        'feedbackPage.review.statusDone': 'done',
        'feedbackPage.review.tags': 'Tags',
        'feedbackPage.review.note': 'Note',
        'feedbackPage.review.notePlaceholder': 'Internal notes',
        'feedbackPage.review.saved': 'Saved',
        'feedbackPage.review.conflict': 'Version conflict',
        'feedbackPage.review.lastReviewedBy': 'Last reviewed by {{actor}} ({{at}})',
        'feedbackPage.stats.title': 'Statistics',
        'feedbackPage.stats.total': 'Total',
        'feedbackPage.stats.positive': 'Positive',
        'feedbackPage.stats.negative': 'Negative',
        'feedbackPage.stats.positiveRate': 'Positive rate',
        'feedbackPage.stats.inbox': 'Inbox',
        'feedbackPage.stats.vsPrevious': 'vs previous period',
        'feedbackPage.stats.topDomains': 'Top negatives — domains',
        'feedbackPage.stats.topIntents': 'Top negatives — intents',
        'feedbackPage.stats.topTools': 'Top negatives — tools',
        'feedbackPage.stats.smallSample': 'small sample',
        'documentsPage.tabSearch': 'Search',
        'documentsPage.tabRegister': 'Register',
        'documentsPage.tabIngestion': 'Review Queue',
        'documentsPage.tabPolicy': 'Policy',
        'documentsPage.tabAnalytics': 'Analytics',
        'documentsPage.bulkSeed.buttonLabel': 'Bulk seed policy',
        'documentsPage.bulkSeed.modalTitle': 'Bulk seed policy documents',
        'documentsPage.bulkSeed.intro': 'Seed multiple policy documents at once.',
        'documentsPage.bulkSeed.pasteTab': 'Paste JSON',
        'documentsPage.bulkSeed.manualTab': 'Manual entry',
        'documentsPage.bulkSeed.pasteLabel': 'JSON input',
        'documentsPage.bulkSeed.cancelLabel': 'Cancel',
        'documentsPage.bulkSeed.submitLabelEmpty': 'Seed entries',
        'documentsPage.addDocument': 'Add Document',
        'documentsPage.batchAdd': 'Batch Add',
        'documentsPage.searchAndDelete': 'Search & Delete Indexed Documents',
        'documentsPage.search': 'Search',
        'documentsPage.searchEmpty': 'No search results',
        'documentsPage.query': 'Query',
        'documentsPage.topK': 'Top K',
        'documentsPage.similarityThreshold': 'Similarity Threshold',
        'documentsPage.content': 'Content',
        'documentsPage.metadataJson': 'Metadata (JSON)',
        'documentsPage.add': 'Add',
        'documentsPage.addBatch': 'Add Batch',
        'documentsPage.documentsJsonArray': 'Documents (JSON Array)',
        'documentsPage.library.title': 'Knowledge documents',
        'documentsPage.library.description': 'Find and review documents used for answers.',
        'documentsPage.library.searchLabel': 'What are you looking for?',
        'documentsPage.library.searchPlaceholder': 'For example, password reset policy',
        'documentsPage.library.advancedSearch': 'Adjust search range',
        'documentsPage.library.resultLimit': 'Number of documents',
        'documentsPage.library.minimumMatch': 'Minimum match',
        'documentsPage.library.resultsTitle': 'Saved knowledge documents',
        'documentsPage.library.savedDescription': 'Select a document to review its content and source.',
        'documentsPage.library.searchResultsDescription': 'Documents closest to your search.',
        'documentsPage.library.summaryAria': 'Knowledge document summary',
        'documentsPage.library.total': 'Total',
        'documentsPage.library.sourceReady': 'Source confirmed',
        'documentsPage.library.sourceNeeded': 'Source needed',
        'documentsPage.library.untitled': 'Untitled document',
        'documentsPage.library.sourceUnknown': 'Source unknown',
        'documentsPage.library.match': 'Match',
        'documentsPage.library.matchValue': 'Match {{value}}',
        'documentsPage.library.detailTitle': 'Document details',
        'documentsPage.library.deleteAction': 'Delete this document',
        'documentsPage.library.noResultsDescription': 'Try a different phrase or broaden the search range.',
        'documentsPage.library.noDocumentsDescription': 'Save the first document to find and manage it here.',
        'documentsPage.library.registerAction': 'Register document',
        'documentsPage.register.title': 'Register knowledge document',
        'documentsPage.register.description': 'Save guidance and policies used for answers.',
        'documentsPage.register.singleTitle': 'New document',
        'documentsPage.register.singleDescription': 'Register one document and verify it immediately.',
        'documentsPage.register.contentLabel': 'Document content',
        'documentsPage.register.contentHint': 'Use a readable title and paragraphs.',
        'documentsPage.register.contentPlaceholder': 'Enter the document content',
        'documentsPage.register.advancedMetadata': 'Source and additional information',
        'documentsPage.register.advancedMetadataDescription': 'Only add JSON when source or classification data is needed.',
        'documentsPage.register.saveAction': 'Save knowledge document',
        'documentsPage.register.batchTitle': 'Register multiple documents',
        'documentsPage.register.batchDescription': 'Advanced JSON batch registration.',
        'documentsPage.register.batchAction': 'Save document batch',
        'documentsPage.register.batchCompleted': 'Documents saved',
        'documentsPage.enableIngestion': 'Enable ingestion capture',
        'documentsPage.requireReview': 'Require review for new candidates',
        'documentsPage.savePolicy': 'Save Policy',
        'documentsPage.resetToDefaults': 'Reset to Defaults',
        'documentsPage.noCandidates': 'No candidates',
        'documentsPage.policyUnavailable': 'Dynamic RAG policy API is not enabled on this server.',
        'documentsPage.ragPolicy': 'RAG Ingestion Policy',
        'documentsPage.policy.title': 'Knowledge collection rules',
        'documentsPage.policy.description': 'Choose which questions and answers become knowledge candidates.',
        'documentsPage.policy.reloadAction': 'Reload current rules',
        'documentsPage.policy.unavailableTitle': 'Collection rules are unavailable',
        'documentsPage.policy.unavailableDescription': 'Check the connection and try again.',
        'documentsPage.policy.formTitle': 'Rules to apply',
        'documentsPage.policy.formDescription': 'Adjust sources and review requirements.',
        'documentsPage.policy.updated': 'Last saved {{value}}',
        'documentsPage.policy.collectEnabled': 'Collect questions and answers',
        'documentsPage.policy.collectEnabledDescription': 'Add conversations from allowed channels to review.',
        'documentsPage.policy.reviewRequired': 'Review before saving',
        'documentsPage.policy.reviewRequiredDescription': 'Only approved items become knowledge.',
        'documentsPage.policy.allowedSources': 'Channels to collect',
        'documentsPage.policy.allowedSourcesDescription': 'Separate channel names with commas.',
        'documentsPage.policy.minimumQuestion': 'Minimum question length',
        'documentsPage.policy.minimumQuestionDescription': 'Shorter questions are not collected.',
        'documentsPage.policy.minimumAnswer': 'Minimum answer length',
        'documentsPage.policy.minimumAnswerDescription': 'Shorter answers are not collected.',
        'documentsPage.policy.excludedPhrases': 'Phrases to exclude',
        'documentsPage.policy.excludedPhrasesDescription': 'Separate sensitive phrases with commas.',
        'documentsPage.policy.unsaved': 'You have unsaved changes',
        'documentsPage.policy.saveAction': 'Save collection rules',
        'documentsPage.policy.maintenanceTitle': 'Restore default rules',
        'documentsPage.policy.maintenanceDescription': 'Remove saved values and use server defaults.',
        'documentsPage.policy.resetAction': 'Use default rules',
        'ragAnalyticsTab.title': 'Knowledge collection overview',
        'ragAnalyticsTab.description': 'Review how knowledge candidates were processed.',
        'ragAnalyticsTab.periodLabel': 'Time range',
        'ragAnalyticsTab.summaryLabel': 'Knowledge processing summary',
        'ragAnalyticsTab.channel': 'Channel',
        'ragAnalyticsTab.total': 'Total candidates',
        'ragAnalyticsTab.knowledgeSaved': 'Saved as knowledge',
        'ragAnalyticsTab.reviewPending': 'Awaiting review',
        'ragAnalyticsTab.excluded': 'Excluded',
        'ragAnalyticsTab.channelComparison': 'Collection by channel',
        'ragAnalyticsTab.channelComparisonDescription': 'Compare saved and pending items over {{count}} days.',
        'ragAnalyticsTab.byChannel': 'Processing by channel',
        'ragAnalyticsTab.emptyTitle': 'No collection history yet',
        'ragAnalyticsTab.emptyDescription': 'Channel processing appears after conversations are collected.',
        'documentsPage.ragCandidates': 'RAG Ingestion Candidates',
        'documentsPage.reload': 'Reload',
        'documentsPage.channel': 'Channel',
        'documentsPage.captured': 'Captured',
        'documentsPage.approve': 'Approve',
        'documentsPage.reject': 'Reject',
        'documentsPage.reviewComment': 'Review Comment',
        'documentsPage.filter': 'Filter',
        'documentsPage.configEnabled': 'Config Enabled',
        'documentsPage.dynamicEnabled': 'Dynamic Enabled',
        'documentsPage.usingStoredPolicy': 'Using Stored Policy',
        'documentsPage.allowedChannels': 'Allowed Channels',
        'documentsPage.minQueryChars': 'Min Query Chars',
        'documentsPage.minResponseChars': 'Min Response Chars',
        'documentsPage.blockedPatterns': 'Blocked Patterns',
        'nav.help.documents': 'Manage documents used for knowledge search.',
        'platformAdminPage.createTenant': 'Create Tenant',
        'promptLabPage.newExperiment': 'New Experiment',
        'promptLabPage.noExperiments': 'No prompt-lab experiments',
        'promptLabPage.createExperiment': 'Create Experiment',
        'nav.tenantAdmin': 'Tenant Analytics',
        'nav.help.tenantAdmin': 'View tenant usage, costs, quality, and quotas.',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.showingCount': 'Showing {{shown}} of {{total}}',
        'common.limitWarning': 'Results limited to {{limit}}',
        'common.statuses.PENDING': 'PENDING',
        'common.statuses.COMPLETED': 'COMPLETED',
        'common.statuses.REJECTED': 'REJECTED',
        'common.total': 'Total',
        'common.enabled': 'Enabled',
        'common.createdAt': 'Created At',
        'tenantAdminPage.tenantScope': 'Tenant Scope',
        'tenantAdminPage.loadDashboards': 'Load Tenant Dashboards',
        'tenantAdminPage.exportExecutions': 'Export Executions CSV',
        'tenantAdminPage.exportToolCalls': 'Export Tool Calls CSV',
        'tenantAdminPage.noOverview': 'No overview data',
        'tenantAdminPage.noUsage': 'No usage data',
        'tenantAdminPage.overview': 'Overview',
        'tenantAdminPage.usage': 'Usage',
        'tenantAdminPage.alerts': 'Tenant Alerts',
        'tenantAdminPage.noActiveAlerts': 'No active tenant alerts',
        'common.loading': 'Loading',
        'common.health': 'Health',
        'common.aria.close': 'Close',
        'common.modal.closeAriaLabel': 'Close',
        'common.aria.loading': 'Loading',
        'common.processing': 'Processing...',
        'common.aria.menu': 'Menu',
        'common.aria.mainNavigation': 'Main navigation',
        'common.aria.clearSearch': 'Clear search',
        'common.aria.pickEmoji': 'Pick emoji',
        'common.aria.systemTopology': 'System topology',
        'common.aria.showAllIssues': 'Show all issues',
        'common.aria.scrollDown': 'Scroll down',
        'issuesPage.topology.centerLabel': 'Reactor',
        'issuesPage.topology.clusterMcpServers': 'MCP SERVERS',
        'issuesPage.topology.clusterGovernance': 'GOVERNANCE',
        'issuesPage.topology.clusterMonitoring': 'MONITORING',
        'issuesPage.topology.legend.healthyNodes': '{{count}} healthy',
        'issuesPage.topology.legend.warningNodes': '{{count}} warn',
        'issuesPage.topology.legend.criticalNodes': '{{count}} critical',
        'issuesPage.topology.legend.nodesSuffix': 'nodes',
        'issuesPage.topology.view.graph': 'Graph',
        'issuesPage.topology.view.list': 'List',
        'issuesPage.topology.view.tablistLabel': 'Topology view',
        'issuesPage.topology.listNode.healthy': 'healthy',
        'issuesPage.topology.listNode.warning': 'warning',
        'issuesPage.topology.listNode.critical': 'critical',
        'issuesPage.topology.listNode.issues': '{{count}} issues',
        'issuesPage.topology.ariaLabel': '{{total}} modules: {{healthy}} healthy, {{warning}} warning, {{critical}} critical',
        'issuesPage.issueCountHeading': 'Issue count',
        'common.a11y.filteredRowCount': 'Showing {{shown}} of {{total}} items',
        'common.a11y.created': 'Created',
        'common.a11y.updated': 'Changes saved',
        'common.a11y.deleted': 'Deleted',
        'common.a11y.bulkApproveResult': '{{succeeded}} of {{total}} approved',
        'common.a11y.bulkRejectResult': '{{succeeded}} of {{total}} rejected',
        'common.a11y.bulkPartialFailure': '{{succeeded}} succeeded, {{failed}} failed',
        'common.bulk.barLabel': 'Bulk actions',
        'common.bulk.selectedCount': '{{count}} selected',
        'common.bulk.clearSelection': 'Clear selection',
        'common.bulk.selectAll': 'Select all',
        'common.bulk.selectRow': 'Select row',
        'common.bulk.actionCompleted': '{{label}} — {{count}} processed',
        'common.a11y.serverConnected': '{{name}} connected',
        'common.a11y.serverDisconnected': '{{name}} disconnected',
        'pageHelp.title': '도움말 / 단축키',
        'pageHelp.noPageContent': 'No help registered',
        'pageHelp.sections.thisPage': '이 페이지',
        'pageHelp.sections.shortcuts': '공통 단축키',
        'pageHelp.shortcuts.cmdK': '명령 팔레트 열기',
        'pageHelp.shortcuts.help': '이 도움말 열기',
        'pageHelp.shortcuts.esc': '모달/오버레이 닫기',
        'pageHelp.shortcuts.arrows': '목록 탐색',
        'pageHelp.shortcuts.enter': '선택',
        'pageHelp.shortcuts.tab': '포커스 이동',
        'common.emptyState.exampleLabel': 'Example preview',
        'common.emptyState.exampleHeading': 'Example',
        'common.emptyState.helpLink': 'View help →',
        'common.emptyState.filteredContext': 'Applied filters',
        'common.emptyState.filteredTitle': 'No items match the filters',
        'common.emptyState.filteredHint': 'Adjust the filters or try again',
        'common.emptyState.clearFilters': 'Clear filters',
        'common.emptyState.filterSummary': '{{summary}}',
        'common.emptyState.forbiddenTitle': '접근 권한이 없어요',
        'common.emptyState.forbiddenContextLabel': '권한 필요',
        'common.emptyState.forbiddenHint':
          '이 영역은 ADMIN 또는 ADMIN_DEVELOPER 역할이 필요합니다',
        'common.emptyState.contactAdmin': '관리자 문의',
        'common.emptyState.forbiddenContext.accessControl':
          '이 페이지는 ADMIN 권한이 필요합니다',
        'common.emptyState.forbiddenContext.mcpServers':
          'MCP 서버 목록 조회는 ADMIN 또는 ADMIN_DEVELOPER 권한이 필요합니다',
        'common.emptyState.forbiddenContext.toolPolicy':
          '도구 정책 조회/편집은 ADMIN 또는 ADMIN_DEVELOPER 권한이 필요합니다',
        'common.emptyState.forbiddenContext.integrations':
          '통합 제어판은 ADMIN 또는 ADMIN_DEVELOPER 권한이 필요합니다',
        'common.emptyState.forbiddenContext.scheduler':
          '스케줄러 작업 관리는 ADMIN 또는 ADMIN_DEVELOPER 권한이 필요합니다',
        'metrics.delta.vsYesterday': '어제 대비',
        'metrics.delta.vsLastWeek': '지난 주 대비',
        'metrics.delta.vsLastMonth': '지난 달 대비',
        'metrics.delta.vsPreviousPeriod': '직전 동일 기간 대비',
        'metrics.delta.tooltipPattern': '{{value}} ({{period}})',
        'onboarding.tour.step1Title': '릴리즈 운영 흐름',
        'onboarding.tour.step1Description': 'release cockpit에서 필수/누락 리포트와 blocker를 확인한 뒤 RAG 수집, 근거 답변, feedback/eval 승격, LangSmith, live smoke 단계로 이어가세요.',
        'onboarding.tour.step2Title': 'Cmd+K 릴리즈 검색',
        'onboarding.tour.step2Description': 'Cmd+K에서 requiredReports, missingReports, langsmith_eval_sync, smoke_run 같은 readiness 용어로 바로 이동하세요.',
        'onboarding.tour.step3Title': '사이드바 탐색',
        'onboarding.tour.step3Description': '릴리즈 운영 그룹의 1-7단계 순서로 admin 화면을 탐색하세요.',
        'onboarding.tour.step4Title': 'API 상태 배지',
        'onboarding.tour.step4Description': 'API 상태를 어디서든 확인할 수 있어요.',
        'onboarding.tour.skip': '건너뛰기',
        'onboarding.tour.previous': '이전',
        'onboarding.tour.next': '다음',
        'onboarding.tour.complete': '완료',
        'onboarding.tour.progress': '{{current}}/{{total}}',
        'layout.globalStatusStrip.mcpLabel': 'MCP',
        'layout.globalStatusStrip.mcpValue': '{{ready}}/{{total}}',
        'layout.globalStatusStrip.issuesLabel': 'Issues',
        'layout.globalStatusStrip.approvalsLabel': 'Approvals',
        'layout.globalStatusStrip.lastUpdatedLabel': 'Updated',
        'layout.globalStatusStrip.aria.label': 'Global system status',
        'layout.globalStatusStrip.aria.mcp': '{{ready}} of {{total}} MCP servers connected',
        'layout.globalStatusStrip.aria.issues': '{{count}} issues',
        'layout.globalStatusStrip.aria.approvals': '{{count}} pending approvals',
        'layout.globalStatusStrip.aria.lastUpdated': 'Updated at {{time}}',
      },
    },
  },
  interpolation: { escapeValue: false },
})

interface WrapperProps {
  children: ReactNode
}

function TestProviders({ children }: WrapperProps) {
  const queryClient = new QueryClient({
    mutationCache: new MutationCache({
      onError: () => {
        // No-op in tests — prevents toast side effects
      },
    }),
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  })

  return (
    <QueryClientProvider client={queryClient}>
      <I18nextProvider i18n={testI18n}>
        {children}
      </I18nextProvider>
    </QueryClientProvider>
  )
}

function customRender(ui: React.ReactElement, options?: RenderOptions) {
  return render(ui, { wrapper: TestProviders, ...options })
}

export * from '@testing-library/react'
export { customRender as render }
export { testI18n as i18n }
